[workspace]
authors = ["grgrzhong <grgrzhong@gmail.com>"]
channels = ["conda-forge","bioconda"]
name = "grgrzhong.github.io"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
render = "quarto render"
preview = "quarto preview"
update = "bash update.sh"

[dependencies]
quarto = ">=1.8.26,<2"
jupyter = ">=1.1.1,<2"
r-base = ">=4.5.2,<4.6"
r-tidyverse = ">=2.0.0,<3"
r-essentials = ">=4.5,<5"
r-downlit = ">=0.4.5,<0.5"
r-xml2 = ">=1.5.0,<2"
r-languageserver = ">=0.3.16,<0.4"
r-httpgd = ">=2.0.4,<3"
r-markdown = ">=2.0,<3"
python = ">=3.14.0,<3.15"
r-reticulate = ">=1.44.1,<2"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest"

[environments]
test = ["test"]
